const formEquipmentOptions = [
  "Pull-up bars",
  "Parallel bars",
  "Push-up bars",
  "Dip bars",
  "Jump boxes",
  "Monkey bars",
  "Ab benches",
  "Balance beams",
  "Rings",
  "Rope climbs",
  "Wall bars",
  "Plyometric boxes",
  "Resistance bands",
  "Parallettes",
  "Kettlebells",
  "Medicine balls",
  "Sandbags",
  "TRX suspension trainers",
  "Foam rollers",
  "Gymnastics rings",
];
