export const formTaskOptions = [
  "Pull-ups",
  "Dips",
  "Push-ups",
  "Box jumps",
  "Monkey bars",
  "Sit-ups",
  "Balance exercises",
  "Ring dips",
  "Rope climbing",
  "Bouldering",
  "Tuck planche",
  "Swings",
  "Medicine ball passes",
  "Bearhug squats",
  "Suspended rows",
  "Self-massage",
  "Front lever",
];
