export const mockSpots = [
  {
    id: 1,
    name: "Trimm-Dich-Pfad",
    address: "Am Planetarium",
    tasks: [
      "Leg raises",
      "Handstand practice",
      "Muscle-up progression",
      "Pistol squats",
    ],
    equipment: ["Pull-up bar", "Parallel bars"],
    imgURL: "../../assets/images/CaliMusterBild.jpeg",
    isBookmark: true,
  },
  {
    id: 2,
    name: "Wehbers Park",
    address: "Emilienstr. 71, 20259 Hamburg",
    task: ["Push-ups", "Dips", "L-sit hold", "Human flag"],
    equipment: ["Pull-up bar", "Parallel bars", "Monkey bars"],
    imgURL: "../assets/images/CaliMusterBild.jpeg",
    isBookmark: false,
  },
  {
    id: 3,
    name: "Altonaer Volkspark",
    address: "Bahrenfeld, 22607 Hamburg",
    task: ["Pull-ups", "Muscle-ups", "Handstand push-ups", "Front lever"],
    equipment: ["Pull-up bar", "Parallel bars", "Rings"],
    imgURL: "../assets/images/CaliMusterBild.jpeg",
    isBookmark: false,
  },
  {
    name: "Park Reeseberg",
    address: "Reeseberg 28, 21079 Hamburg",
    task: ["Squats", "Lunges", "Box jumps", "Plyometric push-ups"],
    equipment: ["Benches", "Steps"],
    imgURL: "../assets/images/CaliMusterBild.jpeg",
    isBookmark: false,
  },
];
