export const mockSpots = [
  {
    id: 1,
    Spotname: "Trimm-Dich-Pfad",
    Address: "Am Planetarium",
    Tasks: [
      "Leg raises",
      "Handstand practice",
      "Muscle-up progression",
      "Pistol squats",
    ],
    Equipment: ["Pull-up bar", "Parallel bars"],
    imgURL: "../../assets/images/CaliMusterBild.jpeg",
    isBookmark: false,
  },
  {
    id: 2,
    Spotname: "Wehbers Park",
    Address: "Emilienstr. 71, 20259 Hamburg",
    Tasks: ["Push-ups", "Dips", "L-sit hold", "Human flag"],
    Equipment: ["Pull-up bar", "Parallel bars", "Monkey bars"],
    imgURL: "../assets/images/CaliMusterBild.jpeg",
    isBookmark: false,
  },
  {
    id: 3,
    Spotname: "Altonaer Volkspark",
    Address: "Bahrenfeld, 22607 Hamburg",
    Tasks: ["Pull-ups", "Muscle-ups", "Handstand push-ups", "Front lever"],
    Equipment: ["Pull-up bar", "Parallel bars", "Rings"],
    imgURL: "../assets/images/CaliMusterBild.jpeg",
    isBookmark: false,
  },
  {
    id: 4,
    Spotname: "Park Reeseberg",
    Address: "Reeseberg 28, 21079 Hamburg",
    Tasks: ["Squats", "Lunges", "Box jumps", "Plyometric push-ups"],
    Equipment: ["Benches", "Steps"],
    imgURL: "../assets/images/CaliMusterBild.jpeg",
    isBookmark: false,
  },
];
